# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jose-vda <jose-vda@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/08/07 13:44:09 by jose-vda          #+#    #+#              #
#    Updated: 2025/08/19 09:31:31 by jose-vda         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	fdf
LIBFT		=	libft/
GNL			=	get_next_line/
MLX			=	minilibx/
LIBFT_A		=	$(addprefix $(LIBFT), libft.a)
GNL_A		=	$(addprefix $(GNL), libgnl.a)
MLX_A		=	$(addprefix $(MLX), libmlx.a)
CC			=	cc
INCLUDE 	=	-Iincludes
CFLAGS		=	-Wall -Wextra -Werror $(INCLUDE) -g
LDFLAGS		=	-L$(LIBFT) -lft -L$(GNL) -lgnl -L$(MLX) -lmlx_Linux -lXext -lX11 -lm -lz
RM			=	rm -f
SRCS		=	src/main.c \
				src/read_map.c \
				src/draw_map.c \

OBJS		=	$(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS) $(LIBFT_A) $(GNL_A) $(MLX_A)
	@$(CC) $(CFLAGS) $(OBJS) $(LDFLAGS) -o $(NAME)
	@echo "Linked into executable \033[0;32mfdf\033[0m."

$(LIBFT_A):
	@$(MAKE) -s -C $(LIBFT)
	@echo "Compiled $(LIBFT_A)."

$(GNL_A):
	@$(MAKE) -s -C $(GNL)
	@echo "Compiled $(GNL_A)."

$(MLX_A):
	@$(MAKE) -s -C $(MLX)
	@echo "Compiled $(MLX_A)."

%.o: %.c
	@$(CC) $(CFLAGS) -c $< -o $@
	@echo "Compiling $<."

localclean:
	@$(RM) $(OBJS)
	@echo "Removed object files."

clean: localclean
	@$(MAKE) clean -s -C $(LIBFT)
	@echo "Clean libft."
	@$(MAKE) clean -s -C $(GNL)
	@echo "Clean gnl."
	@$(MAKE) clean -s -C $(MLX)
	@echo "Clean mlx."

fclean: localclean
	@$(MAKE) fclean -s -C $(LIBFT)
	@echo "Full clean libft."
	@$(MAKE) fclean -s -C $(GNL)
	@echo "Full clean gnl."
	@$(MAKE) clean -s -C $(MLX)
	@echo "Clean mlx."
	@$(RM) $(NAME)
	@echo "Removed executable."

re: fclean all

.PHONY: all clean fclean re localclean bonus